10  POKE 836,0
20  HOME : PRINT  TAB( 142)"C C E" TAB( 201)"S O F T W A R E"
30  PRINT : PRINT : PRINT 
40  PRINT "    CURSO DE BASIC <PARTE 1>"
50  FOR X = 0 TO 1500: NEXT 
1000  CLEAR : GOSUB 9009
1002  PRINT  TAB( 10)"# INDICE #"
1005  PRINT : PRINT "1->  INSTRUCOES PRELIMINARES"
1006  PRINT "2->  HOME"
1008  PRINT "3->  PRINT, SPC, TAB(N)"
1010  PRINT "4->  NUMEROS E NOMES, LET"
1015  PRINT "5->  IF/THEN, AND, OR, NOT"
1017  PRINT "6->  FOR/NEXT, STEP"
1019  PRINT "7->  FUNCOES MATEMATICAS"
1020  PRINT "8->  MATRIZES"
1021  PRINT "9->  MANIPULANDO STRINGS"
1031  PRINT 
1032  GOSUB 9000: PRINT : PRINT "10-> TEMPO"
1034  PRINT "11-> SOUND"
1036  PRINT "12-> FRE, CLEAR"
1038  PRINT "13-> STOP, END, RUN"
1040  PRINT "14-> INPUT"
1042  PRINT "15-> GOTO, ON X GOTO"
1044  PRINT "16-> GOSUB/RETURN, ON X GOSUB"
1046  PRINT "17-> DATA, READ, RESTORE"
1048  PRINT "18-> COMANDOS GRAFICOS"
1054  GOSUB 9000: PRINT : PRINT "19-> EDIT, TRON"
1056  PRINT "20-> NEW, SAVE, LOAD, TLOAD"
1062  PRINT "21-> REM, CHR$(N), ASC"
1064  PRINT "22-> DEBUG"
1068  PRINT : PRINT : PRINT : PRINT : INPUT "DIGITE O NUMERO DO ITEM DESEJADODEPOIS TECLE <RETURN>";A$
1069  IF  VAL (A$) > 22 OR  VAL (A$) < 1 THEN 1000
1070  IF ~20 VAL (A$) >  = 6~20 AND ~20 VAL (A$)~20 =  < 11~20 THEN ~201800
1071  IF ~20 VAL (A$) >  = 12~20 AND ~20 VAL (A$) <  = 17~20 THEN ~201801
1072  IF ~20 VAL (A$)~20 >  = 18~20 AND ~20 VAL (A$) <  = 22~20 THEN ~201802
1075  HOME : ON ~20 VAL (A$) GOTO 1100,1200,1300,1400,1500
1080  GOTO 1000
1100  PRINT "  # INSTRUCOES PRELIMINARES #": PRINT : PRINT "PRIMEIRAMENTE V. DEVE SABER QUE EXISTEM  3 MANEIRAS DE USAR SEU COMPUTADOR : "
1102  PRINT : PRINT "1-> PROGRAMANDO EM BASIC": PRINT : PRINT "2-> PROGRAMANDO EM LINGUAGEM DE     MAQUINA ": PRINT : PRINT "3-> USANDO UM PROGRAMA UTILITA-     RIO(COMO ESTE, POR EXEMPLO)"
1103  GOSUB 9000
1105  PRINT "QUANDO V. LIGA O COMPUTADOR, ELEESTA EM BASIC.PARA VOLTAR A ESTEMODO  DURANTE  A  EXECUCAO DE UMPROGRAMA, DIGITE  <CTRL><C>  E OMESMO NAO SERA APAGADO."
1106  PRINT : PRINT "PARA CONTINUAR A EXECUCAO  USE OCOMANDO #CONT#.": PRINT :~20 PRINT "SE V. QUISER  RETORNAR AO INICIO(ISTO E, AO INDICE) DEVERA DIGI-TAR #RUN# AO INVES DE #CONT#."
1107  GOSUB 9000
1108  PRINT "V. TAMBEM PODE RETORNAR AO BASICTECLANDO  SIMULTANEAMENTE AS TE-CLAS  <SHIFT><RESET>. MAS  NESSECASO, A MEMORIA  SERA  LIMPA  DETODO E QUALQUER DADO."
1109  PRINT : PRINT "SE  DURANTE  OS TESTES  QUE VOCEFIZER APOS O  <CTRL><C>  OCORRERUMA MENSAGEM  DE ERRO, O COMANDO#CONT# NAO TERA EFEITO E VOCE SOPODERA  VOLTAR  AO  PROGRAMA COM#RUN#."
1110  PRINT : GOSUB 9000
1120  PRINT "ESTAS  EXPLICACOES  SAO NECESSA-RIAS PARA QUE V. POSSA USAR ESTEPROGRAMA. A CADA  PASSO, V. SERASOLICITADO A ENTRAR EM BASIC PA-RA APLICAR O QUE APRENDEU."
1121  PRINT "COMECE AGORA:  AO VIRAR ESTA PA-GINA, TECLE <CTRL><C> PARA  SAIRDESTE  PROGRAMA,  DEPOIS  DIGITE#CONT#  <RETURN>  E  VEJA  O QUEACONTECE.V. TERA 3 SEGUNDOS PARATECLAR <CTRL><C>, OU PASSAR PARAA PAGINA SEGUINTE. "
1122  GOSUB 9000: GOSUB 9100
1123  PRINT "ESTA E A PAGINA SEGUINTE A AQUE-LA DA  QUAL V. SAIU DO  PROGRAMAPELA  PRIMEIRA  VEZ.  AGORA SAIAOUTRA VEZ, DIGITE QUALQUER COISA<RETURN>.PROVAVELMENTE V. OBTERA";
1124  PRINT "A MENSAGEM:": PRINT "    SN ERRO - (ERRO DE SINTAXE)": PRINT "AS MENSAGENS DE ERRO REINICIALI-ZAM (RESET) O  PROGRAMA, DE MODOQUE NAO HA COMO  CONTINUAR. POR-TANTO DIGITE #RUN# ";
1125  PRINT "<RETURN> PARAVOLTAR AO INDICE."
1130  GOSUB 9000
1140  GOSUB 9100
1150  GOTO 1000
1200  GOSUB 9009: PRINT  TAB( 11)"# HOME #": PRINT 
1202  PRINT "DIGITANDO #HOME#<RETURN> V. FARACOM QUE A TELA FIQUE LIMPA,COLO-CANDO O  CURSOR NA  POSICAO INI-CIAL DA SEGUNDA LINHA."
1224  PRINT : PRINT "AGORA  ENTRE EM  BASIC E EXPERI-MENTE. ESTA LICAO  TERMINA AQUI.DIGITANDO #CONT#<RETURN> V. PAS-SARA PARA O IMPORTANTE ITEM 3."~20
1226  GOSUB 9000
1227  GOSUB 9100
1229  GOTO 1000
1300  GOSUB 9009: PRINT  TAB( 10)"# PRINT #": PRINT 
1301  PRINT "PRINT XXXXX  FAZ APARECER NA TE-LA A EXPRESSAO XXXXX NAS SEGUIN-TES CONDICOES:": PRINT 
1304  PRINT "1-> SE  XXXXX  FOR UM NUMERO": PRINT : PRINT "2-> SE  XXXXX  FOR UMA EXPRESSAO    NUMERICA OU ALFANUMERICA DE-    LIMITADA POR ASPAS"
1305  GOSUB 9000
1308  PRINT "APOS A  EXECUCAO  DO  COMANDO, OCURSOR SE  POSICIONA NA PRIMEIRAPOSICAO DA LINHA SEGUINTE.": PRINT "SE FOR DIGITADO SEM  XXXXX ,FARAAPENAS COM QUE O CURSOR PULE UMALINHA."
1310  PRINT : PRINT "ENTRE EM BASIC E EXPERIMENTE.": PRINT : PRINT "NAO SE ESQUECA DE TECLAR<RETURN>DEPOIS DE CADA PRINT XXXXX."
1312  GOSUB 9000
1314  GOSUB 9100
1316  PRINT "QUANDO  XXXXX  FOR UMA EXPRESSAOMATEMATICA  NAO  DELIMITADA  PORASPAS, APARECERA  O RESULTADO NATELA, E NAO A EXPRESSAO  COMO V.DIGITOU. ASSIM,  SEU  COMPUTADORFUNCIONA COMO CALCULADORA.": PRINT 
1317  PRINT "VEJA ALGUNS EXEMPLOS, DEPOIS EN-TRE EM BASIC E EXPERIMENTE.": GOSUB 9000
1318  PRINT "PRINT 2+2<RETURN>": PRINT " 4"
1320  PRINT : PRINT "PRINT 4*35<RETURN>": PRINT " 140"
1322  PRINT : PRINT "PRINT -455/5<RETURN>": PRINT "-91"
1323  PRINT : PRINT "PRINT " CHR$ (34)"(4-16)*25" CHR$ (34)"<RETURN>": PRINT "(4-16)*25"
1325  GOSUB 9000
1326  GOSUB 9100
1328  PRINT "V. PODE  COLOCAR  MUITAS EXPRES-SOES EM XXXXX , POR EXEMPLO:"
1340  PRINT : PRINT "PRINT" CHR$ (34)"JA ES" CHR$ (34)"+" CHR$ (34)"TOU N" CHR$ (34)";" CHR$ (34)"A TERCEIRA " CHR$ (34)" " CHR$ (34)"LICAO." CHR$ (34) CHR$ (34)" AGORA SO FALTAM" CHR$ (34)"22-3" CHR$ (34)"LICOES." CHR$ (34)
1344  PRINT : PRINT "O COMPUTADOR RESPONDE:"
1345  PRINT : PRINT "JA ES" + "TOU N";"A TERCEIRA "~20"LICAO."" AGORA SO FALTAM"22 - 3"LICOES.": GOSUB 9000
1346  PRINT : PRINT "OBSERVE QUE A  PALAVRA  'AGORA' FOI  SEPARADA  ERRADAMENTE.  COMPRATICA  V.  APRENDERA  A EVITARQUE ISSO  ACONTECA. POR ENQUANTOEVITE FRASES LONGAS.": PRINT 
1347  PRINT "OBSERVE TAMBEM QUE  22-3  TRANS-FORMOU-SE EM  19. ISSO NAO TERIAACONTECIDO  SE  ESTIVESSE  ENTREASPAS.  AGORA ENTRE EM  BASIC  EEXPERIMENTE."
1348  GOSUB 9000: GOSUB 9100
1350  PRINT "PARA DAR  MAIS DE UMA  INSTRUCAOAO COMPUTADOR  EM UMA SO  LINHA,SEPARE-AS COM : (DOIS PONTOS).  ASSIM:"
1351  PRINT : PRINT "PRINT 40:PRINT"; CHR$ (34);"E O DOBRO"; CHR$ (34);" :PRINT "; CHR$ (34);"DE 20"; CHR$ (34): PRINT : PRINT "A RESPOSTA SERA :": PRINT " 40": PRINT "E O DOBRO ": PRINT "DE 20": GOSUB 9000
1352  PRINT "PARA FAZER  COM QUE ELE NAO MUDEDE LINHA A CADA  INSTRUCAO, USA-SE   ;  (PONTO E VIRGULA) NO FIMDE CADA UMA DELAS. POR EXEMPLO:"
1353  PRINT : PRINT "PRINT" CHR$ (34)"AB" CHR$ (34)";:PRINT" CHR$ (34)"CD" CHR$ (34)";:PRINT 3;:PRINT4-4"
1354  PRINT : PRINT "A RESPOSTA SERA:": PRINT : PRINT "ABCD 3  0": PRINT "(OS NUMEROS APARECEM SEPARADOS)"
1355  GOSUB 9000
1356  PRINT "SE EM  VEZ DE  ';'  USARMOS  ','(VIRGULA),  AS  RESPOSTAS  SERAOTABULADAS  EM  TRES  COLUNAS  NATELA. ENTRE EM  BASIC E TREINE OUSO DOS  SINAIS  QUE V. ACABA DE";
1357  PRINT "APRENDER. SAO SEM DUVIDA OS MAISUSADOS EM  QUALQUER PROGRAMA BA-SIC.": PRINT : PRINT "EM  SEGUIDA  V. APRENDERA  OUTRAFUNCAO DO COMANDO PRINT."
1358  GOSUB 9000: GOSUB 9100
1360  PRINT "PRINT  TAMBEM  FUNCIONA  PARA SESABER O  VALOR  DE UMA VARIAVEL,POR EXEMPLO:"
1361  PRINT : PRINT "X = 1234<RETURN>"
1362  PRINT : PRINT "PRINT X  <RETURN>"
1363  PRINT : PRINT "A RESPOSTA SERA:": PRINT : PRINT " 1234"
1364  GOSUB 9000
1365  PRINT "NA LICAO 4 V. APRENDERA MAIS DE-TALHES DESTA FUNCAO DE  PRINT.  POR ENQUANTO,  VEJAMOS O QUE FAZO COMANDO  SPC."
1366  PRINT "ESTA INSTRUCAO IMPRIME N ESPACOSEM BRANCO DESDE A POSICAO DO EX-TREMO ESQUERDO 0=< N =<255.     DIGITE:"
1367  PRINT : PRINT "PRINT SPC(10);3": PRINT "NO VIDEO APARECERA:": PRINT  SPC( 10)"3"
1368  GOSUB 9000: GOSUB 9100
1369  PRINT "OUTRO COMANDO DE POSICAO E  TAB.PRINT  TAB(N)  XXXXX  IMPRIME  APARTIR DA POSICAO N DA LINHA.": PRINT 
1370  PRINT "SE  N FOR MAIOR QUE 31, O CURSORSE DESLOCA  PARA  AS LINHAS  SE-GUINTES,  CONTANDO ESPACOS.  MASO VALOR MAXIMO PERMITIDO DE  N E255."
1371  PRINT : PRINT "AGORA ENTRE EM BASIC."
1372  GOSUB 9000: GOSUB 9100
1380  GOTO 1000
1400  GOSUB 9009
1410  PRINT  TAB( 13)"# LET #"
1411  PRINT "NO COMANDO PRINT, DEMOS UM EXEM-PLO QUE COMECAVA COM: ": PRINT : PRINT "X=1234 <RETURN>": PRINT : PRINT "QUANDO  V. DEU ESTA INSTRUCAO AOCOMPUTADOR, CRIOU A VARIAVEL X ,COM O VALOR  1234.  V. PODE PEN-SAR  QUE O SINAL  =  TEM A MESMA";
1412  PRINT "FUNCAO EM BASIC QUE EM MATEMATI-CA, MAS NAO E BEM ASSIM .": GOSUB 9000
1413  PRINT "A DIFERENCA MAIS  EVIDENTE E QUEO NOSSO SINAL = NEM SEMPRE E SI-METRICO. O EXEMPLO  DADO NAO PO-DE SER SUBSTITUIDO POR :"
1414  PRINT : PRINT "1234=X <RETURN>": PRINT : PRINT "PORQUE NAO SE PODE CRIAR UMA VA-RIAVEL CHAMADA 1234.": PRINT : PRINT : GOSUB 9000
1415  PRINT : PRINT "NA VERDADE, X=1234  E UMA  ABRE-VIACAO  DE  LET X=1234  (SEJA  XIGUAL AO NUMERO 1234 ). NAS PRI-MEIRAS  VERSOES DO  BASIC, O CO-MANDO  LET  NAO ERA OPCIONAL.": PRINT : PRINT "HOJE E  MANTIDO  POR  TRADICAO ENAO HA VANTAGEM NENHUMA  EM USA-LO.
1416  GOSUB 9000: PRINT "OS NOMES DAS VARIAVEIS NUMERICASSAO  COMPOSTOS DE UM OU MAIS CA-RACTERES, SENDO O  PRIMEIRO  UMALETRA.": PRINT "EXEMPLOS: A, GH, S1, JKV8, CARA,CCE3."
1417  PRINT : PRINT "POREM AS PALAVRAS  RESERVADAS DOBASIC  NAO PODEM  FAZER PARTE DENOMES DE VARIAVEIS POIS O COMPU-TADOR AS CONFUNDIRA COM COMANDOS";: PRINT "EXEMPLO : PA";: INVERSE : PRINT "TO": NORMAL : GOSUB 9000
1418  PRINT "OUTRA DIFERENCA ENTRE = DO BASICE O DA  MATEMATICA E QUE PODEMOSESCREVER O SEGUINTE 'ABSURDO':": PRINT : PRINT "X=X+1": PRINT 
1419  PRINT "ELE NEM ESTRANHA. PARA ELE, O  XDEPOIS DO = E 1234. PORTANTO X+1E 1235.": PRINT : GOSUB 9000
1420  PRINT "JA O X ANTES DO  =  E UMA VARIA-VEL. DEMOS A INSTRUCAO :": PRINT : PRINT "X=1234+1  OU  X=1235": PRINT 
1421  PRINT "O VALOR ANTERIOR DE  X (1234)  EAPAGADO E EM SEU  LUGAR E CARRE-GADO O NOVO VALOR. DIGITE:": PRINT : PRINT "PRINT X <RETURN>": PRINT "A RESPOSTA SERA:": PRINT " 1235"
1422  GOSUB 9000
1423  PRINT "PRATIQUE A ATRIBUICAO DE VALORES(CHAMAM-SE  CONSTANTES) A VARIA-VEIS. E ESSENCIAL.": PRINT : PRINT "DIGITE POR  EXEMPLO:"
1424  PRINT : PRINT "X = 45  <RETURN>": PRINT 
1425  PRINT "Y = -987  <RETURN>": PRINT 
1426  PRINT "AB = X + Y  <RETURN>": PRINT : GOSUB 9000~20
1427  PRINT "XY = 63197  <RETURN>"
1428  PRINT : PRINT "PRINT X; Y; AB + XY - X <RETURN>"
1429  PRINT "PRINT XY + 1000000  <RETURN>"
1430  PRINT : PRINT "PRINT 485 + XY/2 + Y -AB<RETURN>"
1431  PRINT : PRINT "INVENTE  LINHAS  SEGUINDO AS RE-GRAS QUE APRENDEU.": GOSUB 9000: GOSUB 9100
1432  PRINT "CONSTANTES  ALFANUMERICAS   SAO,PARA O COMPUTADOR,  TUDO QUE VEMENTRE  ASPAS.  POR ISSO,  SE  V.DIGITAR:"
1433  PRINT : PRINT "PRINT "; CHR$ (34);"2 + 34 + XY"; CHR$ (34): PRINT : PRINT "ELE RESPONDERA:": PRINT "2 + 34 + XY": PRINT 
1434  PRINT "MAS EM GERAL, USAMOS ESSA FUNCAOPARA OBTER RESPOSTAS LITERAIS.": GOSUB 9000
1435  PRINT "AS VARIAVEIS  ALFANUMERICAS  SE-GUEM AS MESMAS REGRAS  DE NOMEN-CLATURA QUE AS NUMERICAS, EXCETOQUE COLOCAMOS UM 'CIFRAO' DEPOISDO(S)  CARACTER(ES) QUE ESCOLHE-MOS PARA NOMEA-LAS. POR EXEMPLO:"
1436  PRINT "A$ = "; CHR$ (34);"EDGARD"; CHR$ (34);" <RETURN>": PRINT 
1437  PRINT "Z$ = "; CHR$ (34);"LILIAN"; CHR$ (34);" <RETURN>"
1438  PRINT : GOSUB 9000: PRINT 
1439  PRINT "SE AGORA DERMOS A INSTRUCAO :": PRINT : PRINT "PRINT A$ "; CHR$ (34);"AMA"; CHR$ (34);" Z$  <RETURN>": PRINT : PRINT "ELE RESPONDERA :": PRINT : PRINT : PRINT "EDGARD AMA LILIAN": GOSUB 9000
1440  PRINT "ROMANTICO, NAO? AH! EM TEMPO.   AS CONSTANTES ALFANUMERICAS TAM-BEM SE  CHAMAM  'STRINGS'  (COR-DOES). EDGARD NAO SABE,  MAS SEUNOME E UMA STRING.  AGORA  ENTREEM BASIC, INVENTE STRINGS, ATRI-BUA-AS A VARIAVEIS, SEM ESQUECERDE FINALIZA";
1441  PRINT "-LAS COM  $ ."
1442  PRINT : PRINT "ENTAO  FACA O COMPUTADOR  COMPORFRASES COM ESSAS STRINGS ."
1443  GOSUB 9000: GOSUB 9100
1444  PRINT "OS NOMES DE VARIAVEIS  PODEM TERMAIS DE DOIS CARACTERES (TRES,NOCASO DE STRINGS, INCLUINDO O CI-FRAO) MAS O COMPUTADOR SO CONSI-DERA OS  DOIS  PRIMEIROS (E O  $FINAL NO CASO DE STRINGS).": PRINT 
1445  PRINT "ASSIM,  ELE CONFUNDIRA VARIAVEISCUJOS NOMES COMECEM  COM OS DOISMESMOS CARACTERES, POR EXEMPLO :XIZ E XIGLW , AB E ABCDZ , I5SXCTY$ E I5$ , QQQ$ E QQ$."
1446  GOSUB 9000: GOSUB 9100
1447  PRINT "POREM ELE NAO CONFUNDE VARIAVEISNUMERICAS COM ALFANUMERICAS, POREX.: AB COM AB$, X COM X$, ETC.": PRINT 
1448  PRINT "ALIAS,  SE V. DER NOME  ERRADO AUMA VARIAVEL, O COMPUTADOR NAO AACEITARA .": PRINT : PRINT "TENTE CONVENCE-LO DE QUE:": PRINT "R="; CHR$ (34);"ZARATHUSTRA"; CHR$ (34);" OU R$=765": PRINT : PRINT "E VEJA SE FUNCIONA."
1449  GOSUB 9000: GOSUB 9100
1460  PRINT "AQUI  TERMINA  A  LICAO  4. MAISADIANTE V.APRENDERA A USAR VARI-AVEIS  NUMERICAS E A  COMBINAR EDISSECAR STRINGS.": PRINT 
1461  PRINT "SE V. AINDA TIVER DUVIDAS  SOBREESTA  LICAO,  ENTRE EM  BASIC  EPRATIQUE ATE SANA-LAS."
1470  GOSUB 9000: GOSUB 9100
1480  GOTO 1000
1500  GOSUB 9009: PRINT  TAB( 9)"# IF...THEN #"
1501  PRINT : PRINT "O COMANDO  IF...THEN  ESTABELECECONDICOES PARA EXECUTAR DETERMI-NADO(S)  COMANDO(S).  SUA  FORMAMAIS SIMPLES E :": PRINT 
1502  PRINT "IF CCCCC THEN FFFFF"
1503  PRINT : PRINT "ONDE  CCCCC E A CONDICAO E FFFFFE UM COMANDO BASIC, POR EXEMPLO.": GOSUB ~209000
1504  PRINT "EXEMPLOS:": PRINT "=> IF X = 32 THEN HOME"
1505  PRINT "(SE X=32, ENTAO LIMPE A TELA)": PRINT 
1506  PRINT "SE ANTERIORMENTE  X FOI CARREGA-DO COM O VALOR  32, A TELA  SERALIMPA.  SE NAO,  ELE IGNORA ESTAINSTRUCAO.": PRINT 
1507  PRINT "=> IF N1 > 0 THEN N1 = N1 + 3"
1508  PRINT "(SE N1 FOR POSITIVO, ACRESCENTE-LHE O VALOR 3)": GOSUB 9000
1509  PRINT "E CLARO QUE A  VARIAVEL  N1  TEMQUE SER  DEFINIDA ANTES QUE POS-SAMOS USA-LA  COMO CONDICAO.    POR EXEMPLO :": PRINT 
1510  PRINT "N1=9876   <RETURN>"
1511  PRINT : PRINT "IF N1>0 THEN N1=N1+3   <RETURN>"
1512  PRINT : PRINT "PRINT N1   <RETURN>": PRINT 
1513  PRINT " 9879": GOSUB 9000
1514  PRINT "QUANDO  USADO COM O  COMANDO  IF(E COM  QUALQUER  COMANDO EXCETOLET), O SINAL = EQUIVALE AO = DAMATEMATICA. V. PODE DIGITAR:": PRINT 
1515  PRINT "IF N1=0 THEN N1=N1+3 :PRINT N1": PRINT 
1516  PRINT "AGORA ENTRE EM  BASIC  E INVENTECONDICOES,  DEFINA  VARIAVEIS, EFACA O  COMPUTADOR  EXECUTAR (OUNAO)  INSTRUCOES   CONDICIONADASPELO COMANDO IF...THEN."
1517  GOSUB 9000: GOSUB 9100
1518  PRINT "A CONDICAO CCCCC TAMBEM PODE SERCOMPOSTA DE VARIAS RELACOES, SE-PARADAS POR OPERADORES LOGICOS. SAO ELES:"
1519  PRINT : PRINT " AND      (E)": PRINT 
1520  PRINT " OR       (OU)": PRINT : PRINT " NOT      (NAO)": PRINT : GOSUB 9000
1521  PRINT "POR EXEMPLO :": PRINT : PRINT "IF X=32 AND N1=9879 THEN HOME": PRINT : PRINT "NESTE CASO A TELA SO  SERA LIMPASE  AS DUAS  CONDICOES (X = 32 EN1=9879) SE VERIFICAREM.": PRINT 
1522  PRINT "SE  SUBSTITUIRMOS  AND  POR  OR,BASTARA QUE  X = 32 OU N1 = 9879PARA QUE A TELA SEJA LIMPA.": GOSUB 9000
1523  PRINT "O OPERADOR  NOT  NEGA A CONDICAOSEGUINTE. POR EXEMPLO:": PRINT 
1524  PRINT "IF NOT X=N1 THEN HOME"
1525  PRINT : PRINT "(SE  X NAO FOR IGUAL A N1, LIMPEA TELA)": PRINT : PRINT "PODEM-SE COMPOR EXPRESSOES LOGI-CAS EXTREMAMENTE  COMPLEXAS  COMESTES OPERADORES.": GOSUB 9000
1526  PRINT "PARA QUE O  COMPUTADOR NAO FIQUECONFUSO (E V. TAMBEM) USE PAREN-TESES (()) PARA SEPARAR AS RELA-COES."
1527  PRINT : PRINT "ASSIM:": PRINT : PRINT "IF (X>25 AND X<398) OR ((N1=7 ORX<0 (OR NOT(N1=7 AND X=0))  THENHOME": GOSUB 9000
1528  PRINT "SE V. NAO ESTA FAMILIARIZADO COMLOGICA, PASSE ADIANTE. QUANDO V.SOUBER PROGRAMAR, PODERA ESTUDA-LA COM AUXILIO DO COMPUTADOR.": PRINT 
1529  PRINT "MAS SE V. CULTUA A MEMORIA DE A-RISTOTELES, ENTRE EM BASIC E IN-VENTE CONDICOES  COMPOSTAS, PARACONFERIR.": GOSUB 9000: GOSUB 9100
1540  PRINT "PARA O COMPUTADOR, A MENTIRA VA-LE  0  E A VERDADE VALE  1.": PRINT : PRINT "VERIFIQUE DIGITANDO:": PRINT : PRINT "PRINT 45=45   <RETURN> OU"
1544  PRINT "PRINT 45>45   <RETURN>": PRINT : PRINT "NO PRIMEIRO  CASO, ELE  RESPONDE1, E NO SEGUNDO,  0.": PRINT 
1545  PRINT "ENTRE EM BASIC E EXPERIMENTE."
1546  GOSUB 9000: GOSUB 9100
1547  PRINT "PARA  STRINGS, AS RELACOES > E <(MAIOR  E  MENOR QUE) REFEREM-SEAO LUGAR  QUE  OCUPAM, EM  ORDEMALFABETICA. ENTRE EM BASIC E EX-PERIMENTE."
1548  PRINT : PRINT : PRINT "    AQUI TERMINA A LICAO  5.   ": GOSUB 9000: GOSUB 9100
1550  GOTO 1000
1800  GOSUB 9009: PRINT : PRINT ~20"PARA ACESSAR OS ITENS 6 A 11, V.TERA  QUE  CARREGAR  A <PARTE 2>DESTE CURSO.": GOTO ~201850
1801  GOSUB 9009: PRINT ~20: PRINT "PARA ACESSAR  OS ITENS  12 A 17,V. TERA QUE CARREGAR A <PARTE 3>DESTE CURSO.": GOTO ~201850
1802  GOSUB 9009: PRINT : PRINT ~20"PARA ACESSAR  OS ITENS  18 A 22,V. TERA QUE CARREGAR A <PARTE 4>DESTE CURSO.": GOTO 1850
1850  PRINT : PRINT ~20"DIGITE <CTRL><C> PARA ENTRAR  EMBASIC  E  SIGA AS  INSTRUCOES DACAPA DA FITA.": PRINT 
1855  GOSUB ~209000: GOSUB ~209100
1860  GOTO ~201000
9000  PRINT ~20 CHR$ (27) +  CHR$ (61) +  CHR$ (14) +  CHR$ (0);: PRINT "TECLE <RETURN> PARA CONTINUAR";
9001  POKE ~20284,0
9002 FF =  PEEK (284)
9005  IF ~20FF <  > 13~20 THEN ~20 GOTO ~209002
9006  POKE ~20284,0
9009  HOME : INVERSE : PRINT "    CURSO DE BASIC <PARTE 1>    ": NORMAL 
9010  RETURN 
9100  PRINT : PRINT : PRINT : PRINT : PRINT : PRINT "TECLE <CTRL><C> PARA ENTRAR  EM BASIC"
9110  FOR ~20YW = 1~20 TO ~201500: NEXT ~20YW
9120  GOTO 9009
