950  POKE 836,0
960  HOME : PRINT  TAB( 142)"C C E" TAB( 201)"S O F T W A R E"
970  PRINT  TAB( 101)"CURSO DE BASIC <PARTE 4>": FOR I = 0 TO 1500: NEXT 
1000  GOSUB 9008
1001  PRINT  TAB( 10)"# INDICE #": PRINT 
1002  PRINT "1->  INSTRUCOES PRELIMINARES": PRINT "2->  HOME": PRINT "3->  PRINT, SPC, TAB(N)": PRINT "4->  NUMEROS E NOMES, LET": PRINT "5->  IF/THEN, AND, OR, NOT": PRINT "6->  FOR/NEXT, STEP": PRINT "7->  FUNCOES MATEMATICAS": PRINT "8->  MATRIZES"
1003  PRINT "9->  MANIPULANDO STRINGS": GOSUB 9000: PRINT : PRINT "10-> TEMPO": PRINT "11-> SOUND": PRINT "12-> FRE,CLEAR": PRINT "13-> STOP, END, RUN": PRINT "14-> INPUT": PRINT "15-> GOTO, ON X GOTO"
1004  PRINT ~20"16-> GOSUB/RETURN, ON X GOSUB": PRINT ~20"17-> DATA, READ, RESTORE": PRINT "18-> COMANDOS GRAFICOS": GOSUB 9000: PRINT : PRINT "19-> EDIT, TRON"
1006  PRINT "20-> NEW, SAVE, LOAD, TLOAD": PRINT "21-> REM, CHR$(N), ASC": PRINT ~20"22-> DEBUG"
1010  PRINT : INPUT "DIGITE O NUMERO DO ITEM DESEJADOEM SEGUIDA, TECLE <RETURN>";A$
1011  IF ~20 VAL (A$) < 1 OR  VAL (A$) > 22 THEN 1000
1012  IF ~20 VAL (A$)~20 >  = ~201~20 AND ~20 VAL (A$) <  = ~205~20 THEN ~202901
1013  IF ~20 VAL (A$)~20 >  = ~205~20 AND ~20 VAL (A$) =  < ~2011~20 THEN ~202902
1014  IF ~20 VAL ~20(A$)~20 >  = 12~20 AND ~20 VAL (A$)~20 <  = 17~20 THEN ~202903
1015  ON ~20 VAL ~20(A$)~20 - ~2017~20 GOTO ~201100,1200,1300,1400,1500
1050  GOSUB 9006
1100  GOSUB 9008: PRINT  TAB( 5)"# COMANDOS GRAFICOS #": PRINT 
1110  PRINT "AO LIGAR O COMPUTADOR  (OU PRES-SIONAR  <SHIFT><RESET>), A  TELADO COMPUTADOR ESTA NO  MODO NOR-MAL DE TEXTO. O  COMPUTADOR POS-SUI TAMBEM DOIS  MODOS  GRAFICOSDE APRESENTACAO DE DADOS NA TELAQUE SAO:": PRINT 
1115  PRINT "==>GRAFICO DE BAIXA RESOLUCAO": PRINT "==>GRAFICO DE ALTA RESOLUCAO": GOSUB 9000
1120  PRINT "MODO TEXTO:": PRINT : PRINT "NESTE MODO A TELA  APRESENTA CA-RACTERES ALFANUMERICOS E OS SIM-BOLOS ESPECIAIS DO TECLADO (^,%,&, #, ETC)  EM 32 COLUNAS POR 16LINHAS."
1125  PRINT : PRINT "PARA ATIVAR ESTE MODO DIGITE:": PRINT : PRINT "TEXT <RETURN>": GOSUB 9000
1130  PRINT "MODO GRAFICO DE BAIXA RESOLUCAO:": PRINT "NESTE MODO A TELA APRESENTA BLO-COS GRAFICOS,  ASSIM A TELA FICADIVIDIDA EM  128  COLUNAS POR 64LINHAS COM A  POSSIBILIDADE DE 8CORES."
1135  PRINT : PRINT "PARA ATIVAR ESTE MODO DIGITE:": PRINT : PRINT "GR <RETURN>": GOSUB 9000
1137  PRINT "COLOR=": PRINT : PRINT "COM ESTE COMANDO V. PODE DEFINIRA COR DO BLOCO QUE SERA APRESEN-TADO NA TELA (GR).": PRINT : PRINT "COLOR=0 FUNDO   COLOR=1 AMARELO": PRINT "COLOR=2 AZUL    COLOR=3 VERMELHO": PRINT "PARA MUDAR A COR DO  FUNDO E TER";
1138  PRINT "OUTRAS CORES. CONSULTE O  MANUALDE REFERENCIA DO MC-1000.": GOSUB 9000
1140  PRINT "MODO GRAFICO DE ALTA  RESOLUCAO:": PRINT "NESTE MODO A TELA APRESENTA  256POR 192 PONTOS E NAO HA POSSIBI-LIDADE DE SELECAO DE CORES (PRE-TO E BRANCO)."
1141  PRINT : PRINT "PARA ATIVAR ESTE MODO DIGITE:   ": PRINT "HGR <RETURN>": GOSUB 9000
1142  PRINT "PLOT E UNPLOT:": PRINT 
1144  PRINT "ESTAS INSTRUCOES SAO USADAS PARADESENHAR NAS  TELAS DE MODO GRA-FICO. O PLOT  ACENDE UM PONTO OUUMA LINHA E O  UNPLOT  APAGA  UMPONTO OU UMA LINHA.AMBOS POSSUEMTRES FORMATOS DIFERENTES.": PRINT : PRINT "SAO ELES:": GOSUB 9000
1146  PRINT "FORMATO 1 ==> PLOT X,Y": PRINT : PRINT "COLOCA NA TELA UM  PONTO LOCALI-ZADO NAS COORDENADAS X,Y.": PRINT : PRINT "ENTRE NO  BASIC  E  DIGITE A SE-GUINTE LINHA:"
1149  PRINT : PRINT "GR:COLOR=3:PLOT 64,32": PRINT : PRINT "PARA SAIR DO MODO DE BAIXA RESO-LUCAO DIGITE TEXT <RETURN>."
1150  GOSUB 9000: GOSUB 9100
1152  PRINT "FORMATO 2" TAB( 64)"PLOT X1,Y1 TO X2,Y2..XN,YN": PRINT : PRINT "COLOCA UMA LINHA DE (X1,Y1) PARA(X2,Y2)  NA  TELA,  E ASSIM  PORDIANTE.": PRINT : PRINT "N PODERA SER MAIOR OU IGUAL A 2,MAS A INSTRUCAO E  LIMITADA PELOTAMANHO DE UMA LINHA DE PROGRAMA"
1153  GOSUB 9000
1154  PRINT "DIGITE ESTA LINHA:" TAB( 64)"GR : COLOR = 2 : PLOT 32,60  TO 62,10 TO 96,60 TO 28,24 TO 96,24TO 32,60": PRINT : PRINT "VEJA O QUE ACONTECE:": PRINT : PRINT "PARA SAIR DO MODO GRAFICO DIGITETEXT <RETURN>"
1156  GOSUB 9000: GOSUB 9100
1158  PRINT "FORMATO 3" TAB( 64)"PLOT TO XN,YN": PRINT : PRINT "ESTA INSTRUCAO  COLOCARA NA TELAUMA LINHA  INICIANDO  NO  ULTIMOPONTO TRACADO ATE O PONTO XN,YN.SE  NAO  EXISTIR A ESPECIFICACAODE UM PONTO INICIAL,A LINHA PAR-TIRA DO PONTO  (0,0) ATE O ";
1160  PRINT "PONTO(XN,YN).": GOSUB 9000
1170  GOSUB 9100
1175  GOTO 1000
1200  GOSUB 9008: PRINT  TAB( 9)"# EDIT, TRON #": PRINT 
1210  PRINT "PARA  ENTRAR NO MODO  DE EDICAO,V. DEVE DIGITAR:": PRINT : PRINT "EDIT X<RETURN>": PRINT : PRINT "ONDE  X  E O NUMERO DA  LINHA NAQUAL SE DESEJA FAZER A CORRECAO.": GOSUB 9000
1211  PRINT "PRESSIONANDO-SE A TECLA <SPACE>,O CONTEUDO DA LINHA IRA APARECERCARACTER A CARACTER NO VIDEO.": PRINT 
1214  PRINT "NO MODO DE EDICAO, TEMOS ALGUMASFUNCOES QUE NOS FACILITAM O PRO-CESSO DE  EDICAO  E CORRECAO  DELINHAS.": PRINT : PRINT "SAO ELAS:": GOSUB 9000
1216  PRINT "FUNCAO L :" TAB( 64)"MOSTRA O CONTEUDO DA LINHA A SERREVISADA. CASO V. NAO TENHA NADAA CORRIGIR, TECLE  <RETURN>  E ALINHA PERMANECERA INALTERADA."
1217  PRINT : PRINT "FUNCAO I :" TAB( 64)"PERMITE A INSERCAO DE CARACTERESNUMA LINHA. PARA SAIR DESTE MODOTECLE <CTRL><C>.": GOSUB 9000
1220  PRINT "FUNCAO D :" TAB( 64)"APAGA UM CARACTER DA LINHA.": PRINT 
1222  PRINT : PRINT : PRINT "FUNCAO S :" TAB( 64)"SUBSTITUI UM CARACTER POR OUTRO.": GOSUB 9000
1224  PRINT "FUNCAO H :" TAB( 64)"APAGA  TODOS  OS CARACTERES APOSO CURSOR E ENTRA NO  MODO DE IN-SERCAO."
1226  PRINT : PRINT "FUNCAO X :" TAB( 64)"MOSTRA TODOS OS  CARACTERES APOSO CURSOR E ENTRA EM  MODO DE IN-SERCAO.": GOSUB 9000
1228  PRINT "FUNCAO Q :" TAB( 64)"SAI DO MODO DE EDICAO  SEM VALI-DAR QUALQUER  ALTERACAO NA LINHACHAMADA."
1230  PRINT : PRINT "PARA MAIORES INFORMACOES, V. PO-DE  ENCONTRAR NO  MANUAL DE INS-TRUCOES DO SEU MC-1000.": GOSUB 9000
1232  PRINT "TRON :": PRINT 
1234  PRINT "ESTA  INSTRUCAO  PERMITE QUE  V.ACOMPANHE A EXECUCAO DO SEU PRO-GRAMA LINHA A LINHA.": PRINT : PRINT "QUANDO ATIVADA,  ELA APRESENTA ONUMERO DA  LINHA QUE  ESTA SENDOEXECUTADA.": PRINT : PRINT "TRON <RETURN>": GOSUB 9000
1236  PRINT "TROF :" TAB( 64)"DESATIVA A INSTRUCAO TRON.": PRINT : PRINT "TROF <RETURN>": PRINT 
1238  PRINT "ENTRE EM BASIC E FACA UM PROGRA-MA SIMPLES QUE LHE PERMITA APLI-CAR O QUE V. APRENDEU ATE AQUI.": PRINT : PRINT "       FIM DA LICAO 19": GOSUB 9000: GOSUB 9100
1240  GOTO 1000
1300  GOSUB 9008: PRINT "   # NEW, SAVE, LOAD, TLOAD #": PRINT 
1301  PRINT "NEW :" TAB( 64)"APAGA TODO O PROGRAMA.SERVE PARALIMPAR A MEMORIA A FIM DE OCUPA-LA COM OUTRO PROGRAMA SEM PRECI-SAR DESLIGAR O COMPUTADOR."
1302  PRINT : PRINT : GOSUB 9000
1304  PRINT "SAVE :" TAB( 64)"SERVE PARA ARMAZENAR SEU PROGRA-MA BASIC EM FITA. V. DEVE DAR UMNOME PARA IDENTIFICAR O SEU PRO-GRAMA. ESTE  NOME  DEVE  SER UMASEQUENCIA ALFANUMERICA DE NO MA-XIMO 5 CARACTERES.": PRINT : PRINT "POR EXEMPLO:": GOSUB 9000
1305  PRINT "SAVE 123DX <RETURN>" TAB( 64)"ANTES DE PRESSIONAR  <RETURN> V.DEVE APERTAR AS TECLAS  (RECORD)E (PLAY) DO GRAVADOR. O COMPUTA-DOR DARA UM SINAL DE  'OK' QUAN-DO O ARMAZENAMENTO  ESTIVER TER-MINADO."
1306  GOSUB 9000
1307  PRINT "LOAD :" TAB( 64)"CARREGA UM PROGRAMA BASIC DA FI-TA PARA O COMPUTADOR.": PRINT "POR EXEMPLO:": PRINT : PRINT "LOAD 123DX <RETURN>": PRINT 
1308  PRINT "APOS TECLAR <RETURN> PRESSIONE ATECLA (PLAY) DO GRAVADOR.": GOSUB 9000: PRINT "TLOAD :" TAB( 64)"CARREGA  PROGRAMAS EM  LINGUAGEMDE MAQUINA DA FITA PARA O COMPU-TADOR.": PRINT : PRINT "ESTE COMANDO NAO  PRECISA DO NO-ME DO PROGRAMA."
1309  PRINT : PRINT "PARA ARMAZENAR PROGRAMAS EM LIN-GUAGEM DE MAQUINA CONSULTE O MA-NUAL DE REFERENCIA DO MC-1000.": GOSUB 9000
1310  PRINT : PRINT "        FIM DA LICAO 20": GOSUB 9000: GOSUB 9100
1320  GOTO 1000
1400  GOSUB 9008: PRINT  TAB( 5)"# REM, CHR$(N), ASC #": PRINT 
1401  PRINT "REM :" TAB( 64)"COLOCADO  EM  UMA  LINHA,  FAZ OCOMPUTADOR IGNORAR TUDO  QUE ES-TIVER DEPOIS DELE NESSA LINHA.": PRINT : PRINT "SERVE PARA  COLOCAR  COMENTARIOSQUE O AJUDARAO A SE  ORIENTAR NAMANUTENCAO DO SEU PROGRAMA.": GOSUB 9000
1402  PRINT "CHR$(N) :" TAB( 64)"FORNECE O  CARACTER  'ASCII'  DENUMERO 'N'.": PRINT 
1405  PRINT "ASC(" CHR$ (34)"S" CHR$ (34)") :" TAB( 64)"FORNECE O VALOR  'ASCII'  DO CA-RACTER ENTRE PARENTESES."
1410  GOSUB 9000: GOSUB 9100
1420  GOTO 1000
1500  GOSUB 9008: PRINT  TAB( 12)"# DEBUG #": PRINT 
1505  PRINT "PARA QUE  V.  POSSA  DESENVOLVERROTINAS EM LINGUAGEM DE MAQUINA,DIGITE :": PRINT : PRINT "DEBUG <RETURN>": PRINT 
1510  PRINT "QUANDO V. USA ESTA  INSTRUCAO, OCOMPUTADOR SAI DO  BASIC E PASSAA UTILIZAR ...": GOSUB 9000: PRINT "UM PROGRAMA INTERNO QUE PERMITI-RA A V. ESCREVER PROGRAMAS E RO-TINAS EM LINGUAGEM DE MAQUINA.": PRINT 
1515  PRINT "NESTA LICAO  VAMOS  SIMPLESMENTEAPRESENTAR OS COMANDOS DO DEBUG,VISTO  QUE  A FINALIDADE   DESTECURSO E O  BASIC E NAO A LINGUA-GEM DE MAQUINA.": PRINT : PRINT "BEM VAMOS A ELES ..."
1516  GOSUB 9000
1518  PRINT "TODOS OS VALORES E ENDERECOS DOSCOMANDOS DO  DEBUG DEVEM SER DA-DOS EM HEXADECIMAL.": PRINT 
1520  PRINT "COMANDO  D :" TAB( 64)"> DISPLAY DE DADOS": PRINT : PRINT "D XXXX YYYY": PRINT : PRINT "ONDE  XXXX  E O ENDERECO INICIALE  YYYY E O ENDERECO FINAL.": GOSUB 9000
1525  PRINT "COMANDO  F :" TAB( 64)"> COLOCA DADOS.": PRINT : PRINT "F XXXX YYYY DD": PRINT : PRINT "ONDE  XXXX  E O ENDERECO INICIALYYYY  E O ENDERECO FINAL E  DD EO VALOR A SER COLOCADO.": GOSUB 9000
1530  PRINT "COMANDO  S :" TAB( 64)"> SUBSTITUI DADOS.": PRINT : PRINT "S XXXX": PRINT : PRINT "ONDE  XXXX  E O ENDERECO DO DADOA SER SUBSTITUIDO.": GOSUB 9000
1535  PRINT "COMANDO  M :" TAB( 64)"> MOVE BLOCOS DE DADOS.": PRINT : PRINT "M XXXX YYYY DDDD": PRINT : PRINT "ONDE  XXXX  E O ENDERECO INICIALYYYY  E O ENDERECO FINAL E  DDDDE O ENDERECO  INICIAL  PARA ONDEOS DADOS SERAO COPIADOS.": GOSUB 9000
1540  PRINT "COMANDO  G :" TAB( 64)"> EXECUTA O PROGRAMA.": PRINT : PRINT "G XXXX": PRINT : PRINT "ONDE  XXXX  E O ENDERECO INICIALDO PROGRAMA.": GOSUB 9000
1545  PRINT "COMANDO  X :" TAB( 64)"> MOSTRA OU  ALTERA  O VALOR DOSREGISTRADORES DO  Z80-A.": PRINT : PRINT "X     OU  X KK": PRINT : PRINT "ONDE  KK  E O REGISTRADOR  A SERALTERADO. CASO O MESMO SEJA OMI-TIDO, O CONTEUDO DE TODOS OS RE-GISTRADORES SERA MOSTRADO."
1546  GOSUB 9000
1550  PRINT "COMANDO  R :" TAB( 64)"> SIMILAR AO COMANDO  X  PARA OSREGISTRADORES-LINHA.": PRINT : PRINT 
1555  PRINT "COMANDO  Q :" TAB( 64)"> RETORNA PARA O BASIC.": PRINT : PRINT "      ";~20: INVERSE : PRINT "## FIM DO CURSO ##": NORMAL 
1560  GOSUB 9000: GOSUB 9100
1570  GOTO 1000
2901  GOSUB 9008: PRINT : PRINT "PARA ACESSAR  OS ITENS  1  A  5,V. TERA QUE CARREGAR A <PARTE 1>DESTE CURSO.": GOTO 2950
2902  GOSUB 9008: PRINT : PRINT "PARA ACESSAR  OS ITENS  6  A 11,V. TERA QUE CARREGAR A <PARTE 2>DESTE CURSO.": GOTO 2950
2903  GOSUB 9008: PRINT : PRINT "PARA CARREGAR  OS ITENS 12 A 17,V. TERA QUE CARREGAR A <PARTE 3>DESTE CURSO.": GOTO 2950
2950  PRINT : PRINT "DIGITE <CTRL><C> PARA ENTRAR  EMBASIC  E  SIGA AS  INSTRUCOES DACAPA DA FITA.": PRINT 
2960  GOSUB 9000: GOSUB 9100
2970  GOTO 1000
8990  END 
9000  PRINT  CHR$ (27) +  CHR$ (61) +  CHR$ (14) +  CHR$ (0);: PRINT "TECLE <RETURN> PARA CONTINUAR ";
9001  POKE ~20284,0
9003 FF =  PEEK (284)
9004  IF ~20FF <  > 13~20 THEN ~20 GOTO ~209003
9005  POKE ~20284,0
9006  REM  CABECALHO
9008  HOME 
9009  INVERSE : PRINT "    CURSO DE BASIC <PARTE 4>    ": NORMAL 
9010  RETURN 
9100  PRINT : PRINT : PRINT : PRINT : PRINT : PRINT "TECLE  <CTRL><C>  PARA ENTRAR EMBASIC"
9110  FOR YW = 1 TO 1340: NEXT YW
9120  GOTO 9008
