10  POKE 836,0
20  HOME : PRINT  TAB( 142)"C C E" TAB( 201)"S O F T W A R E"
30  PRINT  TAB( 101)"CURSO DE BASIC <PARTE 2>": FOR X = 1 TO 1500: NEXT 
1500  GOSUB 9005
1501  PRINT  TAB( 10)"# INDICE #": PRINT 
1502  PRINT ~20"1->  INSTRUCOES PRELIMINARES": PRINT "2->  HOME": PRINT "3->  PRINT, SPC, TAB(N)": PRINT ~20"4->  NUMEROS E NOMES, LET": PRINT "5->  IF/THEN, AND, OR, NOT": PRINT "6->  FOR/NEXT, STEP"
1503  PRINT "7->  FUNCOES MATEMATICAS": PRINT "8->  MATRIZES": PRINT "9->  MANIPULANDO STRINGS"
1504  GOSUB 9000: PRINT : PRINT "10-> TEMPO"
1505  PRINT "11-> SOUND"
1506  PRINT "12-> FRE, CLEAR"
1507  PRINT "13-> STOP, END, RUN"
1508  PRINT "14-> INPUT"
1509  PRINT "15-> GOTO, ON X GOTO"
1510  PRINT "16-> GOSUB/RETURN, ON X GOSUB"
1511  PRINT "17-> DATA, READ, RESTORE"
1512  PRINT "18-> COMANDOS GRAFICOS"
1513  GOSUB ~209000: PRINT : PRINT "19-> EDIT, TRON"
1514  PRINT "20-> NEW, SAVE, LOAD, TLOAD"
1515  PRINT "21-> REM, CHR$(N), ASC"
1516  PRINT "22-> DEBUG"
1517  PRINT 
1518  PRINT : INPUT "DIGITE O NUMERO DO ITEM DESEJADOEM SEGUIDA, TECLE <RETURN>";A$
1519  IF ~20 VAL (A$) > 22~20 OR ~20 VAL (A$) < 1~20 THEN 1500
1520  IF ~20 VAL ~20(A$)~20 >  = 1~20 AND ~20 VAL (A$)~20 =  < ~205~20 THEN ~202901
1521  IF ~20 VAL (A$)~20 >  = ~2012~20 AND ~20 VAL (A$)~20 <  = ~2017~20 THEN 2902
1522  IF ~20 VAL (A$)~20 >  = ~2018~20 AND ~20 VAL (A$)~20 <  = ~2022~20 THEN ~202903
1530  IF  VAL (A$) > 11 THEN 2900
1540  ON ~20 VAL (A$) - 5 GOTO 1600,1700,1800,1900,2000,2100
1550  GOSUB 9005
1551  PRINT 
1552  PRINT "PARA  ACESSAR OS  ITENS 1 - 5 V.TERA  QUE  RETORNAR  A  PRIMEIRAPARTE DESTE CURSO. RETORNE A FI-TA AO INICIO,  TECLE <CTRL><C> ESIGA AS  INSTRUCOES  DA CAPA  DAFITA."
1554  GOSUB ~209000
1560  GOTO 1500
1600  GOSUB 9005: PRINT  TAB( 9)"# FOR...NEXT #": PRINT 
1601  PRINT "QUANDO  V. QUISER QUE O COMPUTA-DOR EXECUTE UM MESMO COMANDO VA-RIAS VAZES, A MANEIRA MAIS  PRA-TICA SERA USANDO O COMANDO FOR:": PRINT 
1603  PRINT "FOR Y = 1 TO 1000 : PRINT Y :   NEXT Y": GOSUB ~209000
1604  PRINT "EM SEGUIDA,  TECLANDO  <RETURN>,ELE MOSTRARA OS NUMEROS DE  UM AMIL. TODOS OS COMANDOS ENTRE FORE  NEXT  SERAO   EXECUTADOS  MILVEZES. A CADA VEZ, A VARIAVEL  YSERA INCREMENTADA DE 1.": PRINT "SE EM SEGUIDA, V. DIGITAR :"
1605  PRINT : PRINT "PRINT Y <RETURN>": PRINT : PRINT "ELE RESPONDERA :": PRINT " 1001": GOSUB 9000: PRINT 
1606  PRINT "SE, EM LUGAR DE PRINT Y COLOCAR-MOS OUTRO(S) COMANDO(S) COM FUN-COES DE Y, ELE OS EXECUTARA, AS-SUMINDO A CADA  VEZ O VALOR COR-RENTE DE  Y. (Y E SO   UM  EXEM-PLO. V. PODE  USAR QUALQUER  VA-RIAVEL NUMERICA).": PRINT : PRINT "EXPERIMENTE."
1607  PRINT : GOSUB 9000: GOSUB 9100
1608  PRINT "V. PODE COMBINAR MAIS DE UMA VA-RIAVEL ITERATIVA, POR EXEMPLO:": PRINT 
1609  PRINT "FOR X=1 TO 10: FOR Z= 15 TO 183:PRINT X+Z:NEXT Z: NEXT X"
1610  PRINT : PRINT "OBSERVE QUE O  NEXT  MAIS INTER-NO E O QUE  CORRESPONDE  AO  FORMAIS INTERNO. SE NAO OBEDECERMOSESSA REGRA, A INSTRUCAO NAO SERAACEITA.": GOSUB 9000
1611  PRINT "SE V. COLOCAR  COMANDOS INDEPEN-DENTES DAS VARIAVEIS,  POR EXEM-PLO:  PRINT" CHR$ (34)" PROXIMO -->" CHR$ (34)",  ELESSERAO EXECUTADOS DA MESMA FORMA."
1615  PRINT "SE V. NAO COLOCAR NADA(EXCETO :-DOIS PONTOS)  ENTRE OS  COMANDOSFOR E NEXT, FARA  APENAS COM QUEHAJA UMA PAUSA .": PRINT 
1622  PRINT "PEGOU O ESPIRITO DA COISA? ENTREEM BASIC E INVENTE INSTRUCOES.": GOSUB 9000: GOSUB 9100
1623  PRINT "SE V. QUISER  QUE ELE  CONTE PU-LANDO DE N EM N  BASTA ACRESCEN-TAR STEP N AO COMANDO FOR."
1624  PRINT : PRINT "FOR X=21 TO 66 STEP 3: PRINT X: NEXT X"
1625  GOSUB 9000: PRINT "V. TAMBEM PODE  PEDIR UMA CONTA-GEM REGRESSIVA. BASTA QUE O PRI-MEIRO  LIMITE  SEJA  MAIOR QUE OSEGUNDO E QUE  N  SEJA UM NUMERONEGATIVO. EXEMPLO:"
1627  PRINT : PRINT "FOR T=100 TO 1 STEP-1: NEXT T"
1628  PRINT : PRINT "OBSERVE  QUE STEP  -1  NAO E OP-CIONAL COMO  STEP 1.": GOSUB 9000
1630  PRINT : PRINT : PRINT : PRINT : PRINT : PRINT "CHEGAMOS AO FIM DA LICAO 6.     ENTRE EM BASIC E PRATIQUE.": GOSUB 9000: GOSUB 9100
1640  GOTO 1500
1700  GOSUB 9005: PRINT  TAB( 5)"# FUNCOES MATEMATICAS #": PRINT 
1701  PRINT "SEU COMPUTADOR TEM DIVERSAS FUN-COES MATEMATICAS GRAVADAS NA ME-MORIA ROM. SAO AS SEGUINTES:"
1702  PRINT : PRINT "ABS, INT, RND, SGN, SQR": PRINT 
1703  PRINT "EXPONENCIAIS: EXP, LOG": PRINT : PRINT "TRIGONOMETRICAS:  ATN, COS, SIN,TAN": GOSUB 9000
1704  PRINT "ABS(X) FORNECE O MODULO DE X."
1706  PRINT : PRINT "INT(X) FORNECE O  MAIOR  INTEIROMENOR OU IGUAL A X.": PRINT 
1707  PRINT "RND(X) FORNECE UM NUMERO ALEATO-RIO ENTRE 0 E .99999. SE X<0 ELEDEVOLVERA SEMPRE A MESMA SEQUEN-CIA,SE X=0 SERA DEVOLVIDO SEMPREO ULTIMO NUMERO GERADO E  SE X>0SERA  DEVOLVIDO UM  NUMERO QUAL-QUER."
1708  GOSUB 9000: PRINT "SGN(X)  FORNECE  O  SINAL  DE  X(SGN(0)=0, SGN(-7)=-1, SGN(4)=1)"
1709  PRINT "SQR(X) FORNECE A  RAIZ  QUADRADAPOSITIVA DE X"
1710  PRINT : PRINT "EXP(X) ELEVA O ALGARISMO NEPERI-ANO 'E' A POTENCIA X"
1711  PRINT : PRINT "LOG(X) FORNECE O LOGARITMO NEPE-RIANO (NATURAL DE X)": GOSUB 9000
1712  PRINT : PRINT "ANTES DE  PASSARMOS 'AS  FUNCOESTRIGONOMETRICAS, ENTRE EM  BASICE PRATIQUE ESTAS USANDO PRINT.": GOSUB 9000: GOSUB 9100: PRINT "TODOS OS  RESULTADOS  TRIGONOME-TRICOS SAO FORNECIDOS EM RADIANO"
1713  PRINT : PRINT "COS(X) FORNECE O COSSENO DE X.": PRINT : PRINT "SIN(X) FORNECE O SENO DE X.": PRINT : PRINT "TAN(X) FORNECE A TANGENTE DE X.": GOSUB 9000: PRINT "ATN(X) FORNECE O ARCOTANGENTE DEX. O ANGULO ";
1714  PRINT "CUJA TANGENTE E X.  ": PRINT "MAS CUIDADO COM OS  VALORES DE XCUJA FUNCAO TANGENTE NAO E DEFI-NIDA, COMO X=1.5708/2 (X=PI/2). ": PRINT "A RESPOSTA DEPENDERA DA  APROXI-MACAO UTILIZADA.": GOSUB 9000
1715  PRINT "V. PODE  COMPOR  EXPRESSOES  COMMUITAS FUNCOES, POR EXEMPLO:"
1716  PRINT : PRINT "PRINT SQR(SIN(ATN(45))) <RETURN>": PRINT "A RESPOSTA  SERA A RAIZ QUADRADADO SENO DO ANGULO DE TANGENTE 45"
1717  PRINT "ENTRE EM BASIC E FACA O COMPUTA-DOR CALCULAR AS  EXPRESSOES MAISCOMPLICADAS  QUE V. PUDER INVEN-TAR": GOSUB 9000: GOSUB 9100
1718  PRINT "OPERACOES MATEMATICAS DO BASIC: "
1719  PRINT " ^   (POTENCIACAO)": PRINT 
1720  PRINT " /   (DIVISAO)": PRINT 
1721  PRINT " *   (MULTIPLICACAO)": PRINT 
1722  PRINT " -   (SUBTRACAO)": PRINT 
1723  PRINT " +   (ADICAO)"
1724  GOSUB 9000
1725  PRINT "SERAO EXECUTADAS  NESTA ORDEM DEPRIORIDADE, A  MENOS QUE  V. USEPARENTESES PARA  SEPARA-LAS. EN-TAO, SERAO  EXECUTADAS  PRIMEIROAS QUE ESTIVEREM  NOS PARENTESES";
1726  PRINT "MAIS  INTERNOS.  AS FUNCOES  SAOSEMPRE  CALCULADAS  EM  PRIMEIROLUGAR. POR EXEMPLO:": PRINT 
1727  PRINT "37+4/2 = 39   ;  (37+4)/2 = 20.5": GOSUB 9000
1728  PRINT "X*Y^2 = X*Y*Y": PRINT : PRINT "(X*Y)^2 = X*Y*X*Y": PRINT 
1729  PRINT "SIN(X)/2 = METADE DO SENO DE X "
1730  PRINT : PRINT "SIN(X/2) = SENO A METADE DE X "
1731  PRINT : PRINT "2^3/3 = UM TERCO DO CUBO DE Z "
1732  PRINT : PRINT "2*Z^3+1  = 1 + O DOBRO DE Z*Z*Z": GOSUB 9000: PRINT "TAN(A)^3  = O CUBO DA TG. DE A  ": PRINT "TAN(A)/4 = UM QUARTO DA TG. DE A"
1733  PRINT "TAN(Z^3) = TANGENTE DO CUBO DE Z": PRINT "AGORA ENTRE EM  BASIC E TREINE OCALCULO DE EXPRESSOES  MATEMATI-CAS COM E SEM PARENTESES. AS VA-RIAVEIS DEVEM SER  DEFINIDAS AN-TES DE SEREM USADAS.": GOSUB 9000: GOSUB 9100
1734  PRINT "ALEM DESTAS  FUNCOES,  V. PODERACRIAR OUTRAS COM O COMANDO :": PRINT  TAB( 43)"DEF FN": PRINT 
1735  PRINT "POR EXEMPLO, V. PODE PRECISAR DAFUNCAO 'RAIZ CUBICA'. PARA ISSO,BASTA DEFINIR :"
1736  PRINT : PRINT "DEF FN R3(B) = B^(1/3)
1737  GOSUB 9000: PRINT "AO MENCIONAR FN R3(X) , O COMPU-TADOR INTERPRETARA:'A RAIZ CUBI-CA DE X'. B NAO E UMA VARIAVEL."
1738  PRINT "EM SEU  LUGAR PODE  SE POR QUAL-QUER VARIAVEL IGUAL OU DIFERENTEDAQUELAS QUE  V. USOU. NO  NOSSOEXEMPLO, B E O QUE SE CHAMA 'VA-RIAVEL SEM EFEITO'. COMO  VARIA-VEL SEM EFEITO V.PODE USAR QUAL-QUER GRUPO DE CARACTERES ..."
1739  PRINT : GOSUB 9000: PRINT "... SEGUINDO AS REGRAS JA VISTASPARA VARIAVEIS. O NOME DA FUNCAOTAMBEM NAO PODE INCLUIR PALAVRASRESERVADAS DO BASIC.": PRINT 
1740  PRINT "FN  NAO FUNCIONA EM EXECUCAO DI-RETA,  PORTANTO V. SO  PODERA SEEXERCITAR  QUANDO  PASSARMOS  'AEXECUCAO ADIADA. ISTO E,  USANDOLINHAS NUMERADAS PARA  COMPOR UMPROGRAMA.  FIM DA LICAO 7 ."
1741  GOSUB 9000: GOTO 1500
1800  GOSUB 9005: PRINT  TAB( 10)"# MATRIZES #": PRINT 
1801  PRINT "V. PODE ARMAZENAR UM CONJUNTO DECONSTANTES NUMERICAS OU  ALFANU-MERICAS (STRINGS)  NA ORDEM  QUEDESEJAR, USANDO  VARIAVEIS SUBS-CRITAS, ISTO E, VARIAVEIS SEGUI-";
1802  PRINT "DAS DE INDICES (SUBSCRITOS).": PRINT "O CONJUNTO  DE CONSTANTES CHAMA-SE  'MATRIZ'  E APRESENTA GRANDESEMELHANCA COM A MATRIZ DA MATE-MATICA.": GOSUB 9000
1803  PRINT "PARA AVISAR AO  COMPUTADOR QUAN-TOS TERMOS TEM A MATRIZ,  USAMOSO COMANDO DIM NA FORMA:": PRINT 
1804  PRINT "    DIM A$(50)"
1805  PRINT : PRINT "NO  EXEMPLO,  SAO  RESERVADAS 51(DE 0 A 50) POSICOES DE MEMORIA,UMA PARA CADA A$(N).ENTAO V. PO-DERA DEFINIR  CADA TERMO  DA MA-TRIZ A$ COMO FOR CONVENIENTE.": GOSUB 9000
1806  PRINT "POR EXEMPLO:  DIM A$(3) <RETURN> ": PRINT "A$(0)=" CHR$ (34)"GRANDES MUSICOS :" CHR$ (34)":A$(1)=" CHR$ (34)"BEETHOVEN" CHR$ (34)":A$(2)=" CHR$ (34)"LISZT" CHR$ (34)":A$(3)=" CHR$ (34)"OS BEATLES" CHR$ (34)"   <RETURN>"
1807  PRINT : PRINT "SE AGORA DIGITARMOS :": PRINT : PRINT "FOR X=0 TO 3:PRINT A$(X):NEXT X <RETURN>": GOSUB 9000: PRINT "APARECERA NA TELA :": PRINT : PRINT "GRANDES MUSICOS :": PRINT "BEETHOVEN": PRINT "LISTZ": PRINT "OS BEATLES"
1808  PRINT : PRINT "X  PODERIA  SER SUBSTITUIDO  PORQUALQUER VARIAVEL NUMERICA. AGO-RA ENTRE EM BASIC E PRATIQUE.": GOSUB 9000: GOSUB 9100
1809  PRINT "AS MATRIZES NUMERICAS COMPORTAM-SE DA MESMA FORMA :": PRINT 
1810  PRINT "DIM A(40)      <RETURN>": PRINT 
1811  PRINT "FOR X=1 TO 40 : A(X)=X^2:NEXT   <RETURN>": PRINT 
1812  PRINT "ARMAZENA  40  TERMOS COM VALORESDE 1 A 1600  CORRESPONDENTES AOSQUADRADOS DOS INDICES (X).": PRINT : GOSUB 9000
1813  PRINT "OS TERMOS NAO DEFINIDOS (NO CASOA(0)) FICAM COM VALOR = 0 , POR-TANTO, NESTE  EXEMPLO, NAO HAVIANECESSIDADE DE DEFINIR  A(0)=0^2";
1814  PRINT "O COMPUTADOR  NAO CONFUNDE VARI-AVEIS SIMPLES COM SUBSCRITAS.   PODEMOS SUBSTITUIR X POR A. A(A)E PERFEITAMENTE VALIDO.": PRINT : PRINT "ENTRE EM BASIC E EXPERIMENTE.": GOSUB 9000: GOSUB 9100
1815  PRINT "EM MATEMATICA  DEFINEM-SE MATRI-ZES COM TANTAS DIMENSOES QUANTASPUDERMOS IMAGINAR, EM  BASIC, SOESTAMOS LIMITADOS AO  TAMANHO DAMEMORIA.": PRINT 
1816  PRINT "DIM A$(X,Y)     (DUAS DIMENSOES)": PRINT "DIM M(X,Y,Z)    (TRES DIMENSOES)": PRINT "VAMOS CRIAR UMA  MATRIZ  EM DUASDIMENSOES)": GOSUB 9000
1817  PRINT "DIM(5,7)          <RETURN>": PRINT : PRINT "FOR X=1 TO 5:FOR Y=1 TO 7:M(X,Y)=X*Y:NEXTY:NEXTX   <RETURN>": PRINT 
1818  PRINT "PARA VE-LA NA TELA, DIGITE :": PRINT : PRINT "FOR X=1 TO 5:FOR Y=1 TO 7:PRINT M(X,Y);:NEXTY:NEXTX    <RETURN>"
1819  PRINT : PRINT "ENTRE EM BASIC E EXPERIMENTE": GOSUB 9000: GOSUB 9100
1820  PRINT "SAIU MEIO  TORTA, NAO? TENTE EN-DIREITA-LA  SUBSTITUINDO   PRINTM(X,Y) POR PRINT TAB(Y*4)M(X,Y).NAO  FICARA  PERFEITA,  DESCUBRAPORQUE.": PRINT 
1821  PRINT "(NOTE QUE A FORMA  DA MATRIZ DE-PENDE DA ORDEM  DE X E Y NOS CO-MANDOS  FOR  E  NEXT  DE  PRINT,NAO EM 'DIM'  E  M(X,Y)=...).": PRINT 
1822  PRINT "FIM DA LICAO 8": GOSUB 9000: GOSUB 9100
1830  GOTO 1500
1899  HOME 
1900  GOSUB 9005: PRINT  TAB( 5)"# MANIPULANDO STRINGS #": PRINT 
1901  PRINT "LEN(N$)  FORNECE  O  COMPRIMENTODA STRING  N$ , ISTO E, O NUMERODE CARACTERES (INCLUINDO ESPACOSEM BRANCO) QUE COMPOEM N$, P.EX:"
1902  PRINT "PRINTLEN(" CHR$ (34)"COLOR BASIC" CHR$ (34)") <RETURN>"
1903  PRINT "OU:   CB$=" CHR$ (34)"COLOR BASIC" CHR$ (34)" <RETURN>"
1904  PRINT "      PRINTLEN(CB$)   <RETURN>": PRINT 
1905  GOSUB 9000: PRINT "A RESPOSTA SERA:       11": PRINT 
1906  PRINT "VAL(N$)  FORNECE O VALOR NUMERI-CO DO  CONTEUDO  DE  N$,  QUANDOESTE FOR CONSTITUIDO DE ALGARIS-MOS OU OS SINAIS  + E - . QUANDONAO, VAL(N$) SERA IGUAL A ZERO. "
1907  PRINT "STR$(X) , INVERSAMENTE, CONVERTEO NUMERO  X  EM STRING. SE X FORUMA EXPRESSAO MATEMATICA, FORNE-CE A STRING DO RESULTADO."
1908  GOSUB 9000
1909  PRINT "LEFT$(N$,X)  FORNECE OS  X  PRI-MEIROS CARACTERES DE  N$."
1910  PRINT : PRINT "RIGHT$(N$,X)  FORNECE OS  X  UL-TIMOS CARACTERES DE  N$."
1911  PRINT : PRINT "MID$(N$,Y,X)  FORNECE  X  CARAC-TERES DE N$ A PARTIR DO  Y-ESIMOCARACTER.": GOSUB 9000
1912  PRINT "QUANDO V. QUISER QUE  2  OU MAISSTRINGS APARECAM NA TELA UNIDAS,BASTA  COLOCA-LAS  NA  INSTRUCAOPRINT, SEPARADAS OU NAO POR PON-TO E VIRGULA. MAS V. ";
1913  PRINT "PODE PRECI-SAR DE UMA STRING  FORMADA  PELAUNIAO DE DUAS OU MAIS.PARA ISSO,V. DEVE USAR O SINAL + (ADICAO)EXEMPLO:": PRINT 
1914  PRINT "C$=" CHR$ (34)"CURS" CHR$ (34)"+" CHR$ (34)"O DE BASIC" CHR$ (34)" <RETURN>"
1916  GOSUB 9000: PRINT "SE AGORA V. DIGITAR:": PRINT 
1917  PRINT "PRINT C$       <RETURN>": PRINT 
1918  PRINT "A RESPOSTA SERA:": PRINT : PRINT "CURSO DE BASIC": PRINT : PRINT "AGORA ENTRE EM BASIC E PRATIQUE ATE FICAR 'CRAQUE'.": PRINT : GOSUB 9000: GOSUB 9100
1920  PRINT "NO ULTIMO  EXERCICIO  DO ITEM  8V. OBTEVE UMA  MATRIZ  EM QUE ASLINHAS INFERIORES  ESTAVAM SEPA-RADAS. ISSO ACONTECE  PORQUE  OSNUMEROS SAO LADEADOS ";
1930  PRINT "POR ESPACOSEM BRANCO. O ULTIMO  ELEMENTO DECADA  LINHA INVADIA A  LINHA SE-GUINTE.": PRINT : PRINT "SE  V.  SUBSTITUIR   M(X,Y)  PORSTR$(M(X,Y)), CONSEGUIRA UMA MA-TRIZ DE FORMA RETANGULAR."
1931  GOSUB 9000
1937  PRINT "AGORA  ENTRE  EM  BASIC, INVENTEEXPRESSOES ENVOLVENDO LEN, STR$,VAL, E FACA COM QUE O COMPUTADORAS RESOLVA.": PRINT 
1938  PRINT "        FIM DA LICAO  9": GOSUB 9000: GOSUB 9100
1940  GOTO 1500
2000  GOSUB 9005: PRINT  TAB( 12)"# TEMPO #": PRINT 
2002  PRINT "A INSTRUCAO  TEMPO  E USADA PARADEFINIR O EFEITO  ENVELOPE, COM-PASSO E O CANAL DE SOM  UTILIZA-DO.": PRINT : PRINT "O FORMATO E:": PRINT : PRINT "TEMPO A,B,C"
2003  GOSUB 9000
2004  PRINT : PRINT "A--->DEFINE A FREQUENCIA             (0 A 255).": PRINT : PRINT "B--->DEFINE O COMPASSO DO SOM        (0=MAIS RAPIDO, 3=MAIS          LENTO.)": PRINT : PRINT "C--->DEFINE UM DOS TRES CANAIS       (1 A 3)"
2005  PRINT : PRINT "        FIM DA LICAO 10": GOSUB 9000: GOSUB 9100
2010  GOTO 1500
2100  GOSUB 9005: PRINT  TAB( 12)"# SOUND #": PRINT 
2105  PRINT "A INSTRUCAO  SOUND, DEFINE O TOMDA NOTA MUSICAL,  A  POSICAO DOSINTERVALOS (DURACAO), E O  CANALUTILIZADO.": PRINT 
2108  PRINT "O FORMATO E :": PRINT : PRINT "SOUND X,Y,Z": GOSUB 9000: PRINT "X-->DEFINE O TOM DA NOTA": PRINT : PRINT "Y-->DEFINE A DURACAO DA NOTA        (0=MAIS CURTO, 255=MAIS         LONGO)"
2110  PRINT : PRINT "Z-->DEFINE OS CANAIS DE SOM         (1 A 3)": PRINT 
2112  PRINT "EXISTEM AO TODO  96  NOTAS EM  8OITAVAS."
2114  PRINT "       FIM DA LICAO  11": GOSUB 9000: GOSUB 9100
2116  GOTO 1500
2900  GOSUB 9004
2901  GOSUB 9005: PRINT : PRINT "PARA ACESSAR  OS ITENS  1  A  5,V. TERA QUE CARREGAR A <PARTE 1>DESTE CURSO.": GOTO 2950
2902  GOSUB 9005: PRINT : PRINT "PARA ACESSAR  OS ITENS  12 A 17,V. TERA QUE CARREGAR A <PARTE 3>DESTE CURSO.": GOTO 2950
2903  GOSUB 9005: PRINT : PRINT "PARA ACESSAR  OS ITENS  18 A 22,V. TERA QUE CARREGAR A <PARTE 4>DESTE CURSO.": GOTO 2950
2950  PRINT : PRINT ~20"DIGITE <CTRL><C> PARA ENTRAR  EMBASIC  E  SIGA AS  INSTRUCOES DACAPA DA FITA."
2960  GOSUB 9000: GOSUB 9100
2970  GOTO 1500
3400  END 
9000  PRINT  CHR$ (27) +  CHR$ (61) +  CHR$ (14) +  CHR$ (0);: PRINT "TECLE <RETURN> PARA CONTINUAR ";
9001  POKE ~20284,0
9002 FF =  PEEK (284)
9003  IF ~20FF <  > 13~20 THEN ~209002
9004  POKE ~20284,0
9005  HOME 
9006  INVERSE : PRINT "    CURSO DE BASIC <PARTE 2>    ": NORMAL 
9008  RETURN 
9100  PRINT : PRINT : PRINT : PRINT : PRINT : PRINT "TECLE <CTRL><C>  PARA ENTRAR  EMBASIC"
9102  FOR YW = 1~20 TO ~201340: NEXT YW
9104  GOTO 9005
