0  REM ************************
1  REM **     - CCESOFT -    **
2  REM **  FELIPE ABRAMVET   **
3  REM ** VERSAO 1.0   04/85 **
4  REM ************************
5  REM **    DEMO PRINTER    **
6  REM ************************
7  HOME : PRINT  TAB( 11)"- CCESOFT -": PRINT 
8  PRINT "NAO RODE ESTE PROGRAMA SEM ANTES VERIFICAR SE A IMPRESSORA ESTA CONECTADA.": PRINT "CASO CONTRARIO O PROGRAMA TRAVA--RA"
10  INPUT "DIGITE SEU NOME ";A$
11  REM .........SAIDA PARA IMPRESSORA..........
12  REM +++++++CARACTERES DE CONTROLE PARA GRAFIX+++++++++
13  REM  CHR$(15)-SELECIONA A IMPRESSORA P/ LETRA REDUZIDA
14  REM  CHR$(18)-SELECIONA A IMPRESSORA P/ LETRA NORMAL
15  REM   CHR$(7)-ACIONA O BIP DA IMPRESSORA
16  REM   CHR$(27) CHR$(64)-SELECIONA MODO NORMAL DA IMPRESSORA
17  REM   CHR$(157)-IMPRIME O A ACENTUADO
18  REM   CHR$(190)-IMPRIME O C CIDILHA
19  REM .........LINHA 1..........
20  PR# 1: PRINT  CHR$ (7); CHR$ (15);"OL"; CHR$ (157);" "; CHR$ (14);A$; CHR$ (15) CHR$ (27);"  EU SOU O "; CHR$ (18);"MC-1000"; CHR$ (15);" DA CCE."
21  REM ........LINHA 2.........
22  PRINT :
30  PR# 1: PRINT  CHR$ (14); SPC( 9);"ALGUMAS DAS MINHAS CARACTER" CHR$ (149)"STICAS:"
31  REM ........LINHA 3.........
32  PRINT :
40  PRINT  TAB( 3);" SOU O UNICO MICRO COMPUTADOR QUE POSSUI 3 MICROPROCESSADORES."
45  REM .........LINHA 4..........
46  PRINT :
50  PR# 1: PRINT  TAB( 3);" POSSUO CAPACIDADE PARA GERAR GRAFICOS E DESENHOS COM ATE 9 CORES."
51  REM .........LINHA 6...........
52  PRINT : PRINT  TAB( 3);" POSSO AUMENTAR MINHA CAPACIDADE DE MEMORIA ATE 64K."
55  REM .........LINHA 5..........
56  PRINT :
60  PRINT  TAB( 3);" TENHO FUN" CHR$ (190); CHR$ (252);"E";"S ESPECIAIS PARA SOM E CORES."
65  REM ..........LINHA 7.........
66  PRINT :
70  PRINT : PRINT  CHR$ (14);"             FIM DA DEMONSTRA" CHR$ (190); CHR$ (163);"O DA INTERFACE DE IMPRESSORA."
75  PRINT  CHR$ (18): PRINT "      TAMBEM DOU BONS PALPITES PARA A LOTO:"
76  REM ........ESCOLHA DOS NUMEROS DA LOTO........
80  FOR I = 1 TO 5
90 A(I) =  INT ( RND (8) * 99)
95  IF I >  = 2 THEN  GOSUB 200
100  PRINT  CHR$ (27) CHR$ (64)
105  PRINT  CHR$ (7); CHR$ (15); CHR$ (14); CHR$ (27); CHR$ (18);A(I)
110  NEXT I
111  PRINT "*********************************************************************************"
120  PRINT  CHR$ (27) CHR$ (64)
125  END 
199  REM .....SUB ROTINA PARA EVITAR REPETICAO DOS NUMEROS.......
200  FOR G = 1 TO I
210  IF A(I) = A(I + 1) THEN  GOTO 90
220  RETURN 
