0  REM ************************
1  REM *     - CCESOFT -      *
2  REM *OTTO LONGO SERNATINGER*
3  REM *  VERSAO 1.1   04/85  *
4  REM ************************
5  REM *       NEGATIVO       *
6  REM ************************
7  HOME : PRINT : PRINT  TAB( 11)"- CCESOFT -": INVERSE : PRINT : PRINT  TAB( 12)"NEGATIVO"; SPC( 12): NORMAL : PRINT 
10  PRINT : PRINT  TAB( 6)"ENTRE COM UMA PALAVRA"
12  PRINT  TAB( 8)"DE ATE' 15 LETRAS
14  REM 
15  REM ENTRADA DE DADOS
16  REM 
20  PRINT : INPUT "QUAL A PALAVRA ";A$: HOME 
22  REM 
23  REM CONSISTENCIA
24  REM 
25  IF  LEN (A$) > 15 THEN  RUN 
27  REM 
28  REM SAIDA DE DADOS
29  REM 
30  PRINT "TELA NORMAL : ";A$
40  PRINT : PRINT "TELA INVERTIDA : ";: INVERSE : PRINT A$
50  NORMAL 
54  REM 
55  REM  OPCAO DE VOLTA
56  REM 
60  PRINT : PRINT : INPUT "NOVAMENTE S/N ";A$
70  IF A$ = "S" THEN  CLEAR : HOME : GOTO 20
80  HOME 
