0  REM ************************
1  REM *     - CCESOFT -      *
2  REM *OTTO LONGO SERNATINGER*
3  REM *  VERSAO 1.1   05/85  *
4  REM ************************
5  REM *     NUMERO OCULTO    *
6  REM ************************
10  HOME 
15  PRINT  TAB( 11)"- CCESOFT -": PRINT 
20  PRINT  TAB( 9)"TENTE DESCOBRIR
30  PRINT  TAB( 9)"O NUMERO OCULTO
40  PRINT  TAB( 7)"DENTRO DO INTERVALO
50  PRINT : PRINT "O EXTREMO INFERIOR E' 0"
60  INPUT "QUAL O EXTREMO SUPERIOR ";S
70  IF S < 2 THEN  RUN 
80 N =  INT ( RND (8) * (S - 1) + 1)
90 MAX = S
100  HOME : PRINT "O NUMERO ESTA' ENTRE"
110  PRINT MIN;"E";MAX: PRINT 
120  INPUT "QUAL SEU PALPITE ";P
130 NP = NP + 1
140  IF P = N THEN  GOTO 1000
150  IF P < MAX AND P > N THEN MAX = P: GOTO 100
160  IF P > MIN AND P < N THEN MIN = P
200  GOTO 100
1000  HOME : PRINT "VOCE ACERTOU EM";NP;"TENTATIVAS"
1010  PRINT : PRINT  TAB( 7);: INPUT "NOVAMENTE S/N ";A$
1020  IF A$ = "S" THEN  RUN 
1030  HOME 
