0  REM ************************
1  REM *     - CCESOFT -      *
2  REM *OTTO LONGO SERNATINGER*
3  REM *  VERSAO 1.1   04/85  *
4  REM ************************
5  REM *       ESPELHO        *
6  REM ************************
10  HOME : PRINT : PRINT  TAB( 11)"- CCESOFT -": INVERSE : PRINT : PRINT  TAB( 13)"ESPELHO"; SPC( 12): NORMAL 
15  PRINT : PRINT : PRINT  TAB( 6)"ENTRE COM UMA PALAVRA"
16  PRINT  TAB( 12)"QUALQUER"
17  REM 
18  REM ENTRADA DE DADOS
19  REM 
20  PRINT : INPUT "QUAL A PALAVRA ";A$: HOME 
24  REM 
25  REM "LOOP" DE INVERSAO
26  REM 
30  FOR A =  LEN (A$) TO 1 STEP  - 1
40 Z$ = Z$ +  MID$ (A$,A,1)
50  NEXT A
54  REM 
55  REM ROTINA DE SAIDA
56  REM 
60  HOME 
70  PRINT : PRINT : PRINT "A PALAVRA ERA ";A$
80  PRINT : PRINT : PRINT "AGORA E' ";Z$
84  REM 
85  REM  OPCAO DE VOLTA
86  REM 
90  PRINT : PRINT : INPUT "NOVAMENTE S/N ";A$
100  IF A$ = "S" THEN  CLEAR : HOME : GOTO 20
110  HOME 
