10 TEXT : HOME : POKE 245,65: REM SEMIGRAPHICS 4
20 CENTER = 8:RIGHT = 4:DOWN = 2:CHAR = 128
30 WALL = CENTER + DOWN:ALLOWED = 3
40 ON RND (1) * ALLOWED GOTO 60,70: REM NEXT WALL PIECE WILL GO RIGHT-, DOWN- OR LEFTWARDS?
50 PRINT CHR$ (CHAR + WALL);:WALL = CENTER + RIGHT:ALLOWED = 2: GOTO 40
60 PRINT CHR$ (CHAR + WALL);:WALL = CENTER + DOWN:ALLOWED = 3: GOTO 40
70 WALL = WALL + RIGHT: PRINT CHR$ (CHAR + WALL);:WALL = CENTER:ALLOWED = 3: GOTO 40